version: '2.1'
services:
  postgres:
    image: postgres:10.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - $HOME/databases/postgres/portfolio-service/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=portfolio-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks:
      - portfolio-service-network

  portfolio-service:
    image: lpfjustino/portfolio-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/portfolio-service
    networks:
      - portfolio-service-network
    depends_on:
      - postgres

networks:
  portfolio-service-network:
    driver: bridge