spring:
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: "jdbc:postgresql://localhost:5432/portfolio-service"
        username: ${service.db.username}
        password: ${service.db.password}
        drive-class-name: "org.postgresql.Driver"
